### ISSUE TITLE
Adding screenshots to Jupyter notebook kernel

### ISSUE THREAD

**Issue by jet2016** [learn-co-curriculum/dsc-1-01-05-setting-up-environment#3]
I’m thinking if we can include screenshots of the drop-down menu in Jupyter notebook to show where to find the “learn” environment and even select it. @jeff.herman does this in the first part of his Linear Regression video

https://wework.zoom.us/recording/share/MawxGnGauckaRqJD-jQYajnDW3xXq3wJYIva2j1e0JGwIumekTziMw?startTime=1541640756000

**Comment by PeterBell** [comment]
Thanks for doing so!!!
